import type { Metadata } from 'next'
import { Flex, Box } from '@chakra-ui/react'
import { Provider } from '@/components/ui/provider'

import Sidebar from '@/components/Sidebar'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Flex>
            <Sidebar />
            <Box
              ml={{ base: 0, md: 64 }}
              p="4"
              flex="1"
            >
              {children}
            </Box>
          </Flex>
        </Provider>
      </body>
    </html>
  )
}
