import { LinkItem } from '@/models/types'
import {
  Call,
  Category,
  Edit,
  Folder2,
  MenuBoard,
  MessageEdit,
  Note,
  NotificationBing,
  People,
  Stickynote,
  Task,
  TaskSquare,
} from 'iconsax-reactjs'

export const links: LinkItem[] = [
  { label: 'Home', icon: Category, href: '/' },
  { label: 'MKVanBinnen', icon: Stickynote, href: '/mk-van-binnen' },
  { label: 'Document Management', icon: Folder2, href: '/document-management' },
  { label: 'Patient Information', icon: People, href: '/patient-information' },
  { label: 'Agenda', icon: Note, href: '/agenda' },
  { label: 'My Department', icon: Task, href: '/department' },
  { label: 'News', icon: undefined, href: '/department/news' },
  { label: 'Members', icon: undefined, href: '/department/members' },
  { label: 'Todo', icon: undefined, href: '/department/todo' },
  { label: 'Form Task', icon: undefined, href: '/department/form-task' },
  { label: 'Agenda', icon: undefined, href: '/department/agenda' },
  {
    label: 'Follow up system',
    icon: undefined,
    href: '/department/follow-up-system',
  },
  { label: 'Group Settings', icon: undefined, children: [] },
  { label: 'Phone numbers', icon: Call },
  { label: 'My todo Protocols', icon: TaskSquare },
  { label: 'My Notifications', icon: NotificationBing },
  { label: 'Knowledge Base', icon: MenuBoard },
  { label: 'Super Admin', icon: MessageEdit },
  { label: 'Admin', icon: Edit, children: [] },
  { label: 'Agenda', icon: undefined },
  { label: 'News', icon: undefined },
  { label: 'Poll', icon: undefined },
  { label: 'Department Rules', icon: undefined },
  { label: 'Follow up system', icon: undefined },
]
